# .gitlab-ci.yml — minimal Pages for plain HTML/CSS
image: alpine:latest

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r * public || true   # copy root files into public/
  artifacts:
    paths:
      - public
  only:
    - main   # change to 'master' if that’s your default branch
